# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "EC2ssh"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ramon Salvad\u{f3}"]
  s.date = "2014-04-03"
  s.description = "Since ec2 instance public hostnames are dynamic, and not easy to remember or type, this script provides a list all your running instances so you can select the one you want to ssh into easily (without having to pass the aws console ritual each time you need the hostname)."
  s.email = "rsalvado@gnuine.com"
  s.executables = ["ec2ssh"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "EC2ssh.gemspec",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/ec2ssh",
    "lib/ec2ssh.rb",
    "lib/templates/ec2ssh_config_sample.yaml"
  ]
  s.homepage = "http://github.com/rsalvado/ec2ssh"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "A script to make it easier to ssh into running amazon EC2 instances."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<highline>, [">= 1.5.2"])
      s.add_runtime_dependency(%q<aws>, [">= 2.5.6"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.14"])
      s.add_runtime_dependency(%q<terminal-table>, [">= 1.4.5"])
    else
      s.add_dependency(%q<highline>, [">= 1.5.2"])
      s.add_dependency(%q<aws>, [">= 2.5.6"])
      s.add_dependency(%q<activesupport>, [">= 2.3.14"])
      s.add_dependency(%q<terminal-table>, [">= 1.4.5"])
    end
  else
    s.add_dependency(%q<highline>, [">= 1.5.2"])
    s.add_dependency(%q<aws>, [">= 2.5.6"])
    s.add_dependency(%q<activesupport>, [">= 2.3.14"])
    s.add_dependency(%q<terminal-table>, [">= 1.4.5"])
  end
end

